USE DB_03358b_RodolfoReis;

CREATE TABLE IF NOT EXISTS LIVROS(
ID INT auto_increment PRIMARY KEY,
TITULO TEXT NOT NULL,
AUTOR TEXT NOT NULL,
ANO_PUBLICACAO int,
DISPONIVEL BOOLEAN default	TRUE
);

INSERT INTO LIVROS(TITULO, AUTOR, ANO_PUBLICACAO, DISPONIVEL) 
VALUES('O Apanhador no campo de centeios','JD SALINGER',1951,1),('A abolição do homem','CS Lewis',1943,2), ('O homem mais rico da babilonia','George S clason',1926,1);

#PARA ADICIONAR A COLUNA GENERO NA TABELA LIVROS JÁ EXISTENTE
ALTER TABLE LIVROS ADD COLUMN GENERO TEXT;

#PARA INSERIR AS INFORMAÇÕES NA COLUNA GENERO ATUALIZANDO A TABELA
UPDATE LIVROS SET GENERO = 'Romance' WHERE id = 1;
UPDATE LIVROS SET GENERO = 'Ensaio' WHERE id = 2;
UPDATE LIVROS SET GENERO = 'Finanças' WHERE id = 3;

#listar todos os livros da tabela
select *from LIVROS;

#listar livros de determinado autor
SELECT * FROM LIVROS WHERE AUTOR = 'JD SALINGER';

